### ISSUE TITLE
How can PhantomJS.NetCore be used with .NET5

### ISSUE THREAD

**Issue by ghisbo** [TheSalarKhan/PhantomJs.NetCore#3]
This looks great work. 

I have a application in .NET5 on Win and Linux and i would like to try the PhantomJS.NetCore.
Is this possible and how? 

best regards

**Comment by TheSalarKhan** [comment]
Hi there! Thank you for your interest. I've never used .NET5 and I don't know if you can use nuget packages on it. However, nuget or not, you can take the core files from this repo and add them to your project. Its based on three core files
```
Consts.cs
PdfGenerator.cs
PdfGeneratorParams.cs
```

Apart from these there's a 'Resources' folder at the very top that contains zipped binaries you must include that too. Those binaries do the actual html <> pdf conversion.

**Comment by ghisbo** [comment]
I tried but get 

Auto configuration failed
140185264009152:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory

looks as ssl problem. Will look further into it and come back if solved .

**Comment by ghisbo** [comment]
this solved it: 
export OPENSSL_CONF=/dev/null

#https://github.com/bazelbuild/rules_closure/issues/351#issuecomment-854628326
